#version: '3'  # version of compose format 

api-service:
  build: ./api  
  volumes:
    - ./api:/usr/src/app 
  ports:
    - 5001:80  # host:container
  links:
    - db

consumer:
  image: php:apache  
  volumes:
    - ./consumer:/var/www/html 
  ports:
    - 5000:80  # host:container
  links:
    - api-service

app:
  build: ./app
  command: python3 -u ./app/app.py
  ports:
    - "5002:80"
  volumes:
    - .:/todo
  links:
    - db

db:
  image: mongo:3.4.13
